version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    ports:
      - 5601:5601
  twitter-consumer:
    image: vaomaohao/twitter-consumer:new
    ports:
      - 8080:8080
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
      - BATCH_COUNT=100
      - BATCH_INTERVAL=3000